name: Node.js CI

on:
  pull_request:
  push:
    branches: 
      - master
      - staging

jobs:
  build:

    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: node app.js
    - run: node multi.js
    - run: node calc.js
      env:
        CI: true
